/* Copyright (C) YOOtheme GmbH, YOOtheme License */

jQuery(function(a){a.cart({checkout:function(){var m=a(document.body).append('<form name="cart" method="post" style="display:none; "><input type="hidden" name="order_data" value="" /></form>').find('form[name="cart"]');a("input",m).val(JSON.stringify({items:this.items}));m.attr("action","https://www.yootheme.com/component/cart/checkout").submit()}})});
(function(a){var m=null,k={id:"cart",taxRate:0,currency:"EUR",currencySymbol:"\u20ac",checkout:function(){},modalSelector:".cart-modal",modalTemplate:'<div class="cart-modal"><h1>Your Shopping Cart</h1><div class="box"><table><tbody data-cart="items" /></table></div><div class="total" data-cart="total" /><div class="checkout"><a class="button-blue" data-cart="checkout" href="#">Proceed to Checkout</a></div></div>',modalBgSelector:".cart-modal-bg",modalBgTemplate:'<div class="cart-modal-bg" />',itemTemplate:'<tr class="item"><td class="name">{name}</td><td class="price">{price}</td><td class="quantity">{quantity}</td><td class="decrement" data-cart="decrement"></td><td class="increment" data-cart="increment"></td><td class="total">{total}</td><td class="remove" data-cart="remove"></td></tr>',
emptyTemplate:'<div class="empty">You don\'t have any items in your cart.</div>'},p=function(b){a.extend(this,{options:a.extend({},k,b),storage:sessionStorage,items:[],quantity:0,total:0,subTotal:0,taxTotal:0});this.modal=a(this.options.modalSelector);if(!this.modal.length)this.modal=a(this.options.modalTemplate).appendTo("body");this.load();this.refresh()};p.prototype=a.extend(p.prototype,{add:function(b){var b=new j(b),a=this.find(b.code);a?a.quantity+=b.quantity:this.items.push(b);this.save();
this.refresh();this.open(this.modal);return this},remove:function(b){b>-1&&Array.remove(this.items,b);this.save();this.refresh();return this},find:function(b){var f=null;a.each(this.items,function(a,e){e.code==b&&(f=e)});return f},open:function(b){var f=a(document),d=a(this.options.modalBgSelector),e=parseInt(b.css("top")),h=b.height()+e,i=!1;d.length||(d=a(this.options.modalBgTemplate).appendTo("body"));b.bind({"open.modal":function(){b.unbind("open.modal");i||(i=!0,b.css({top:f.scrollTop()-h,opacity:0,
visibility:"visible"}).delay(150).animate({top:f.scrollTop()+e+"px",opacity:1},300,function(){i=!1}),d.fadeIn(150))},"close.modal":function(){b.unbind("close.modal");f.unbind(".modal");i||(i=!0,b.animate({top:f.scrollTop()-h+"px",opacity:0},150,function(){b.css({top:e,opacity:1,visibility:"hidden"});i=!1}),d.delay(300).fadeOut(300))}}).trigger("open");d.unbind(".modal").bind("click.modal",function(){b.trigger("close.modal")});f.bind("keyup.modal",function(g){g.which===27&&b.trigger("close")})},refresh:function(){var b=
this,f=this.options.currencySymbol,d=a('[data-cart="items"]').empty();this.items.length==0&&d.append(b.options.emptyTemplate);a.each(this.items,function(e,h){var i=d.append(a.template(b.options.itemTemplate,a.extend({},h,{price:Number.toCurrency(h.price,f),total:Number.toCurrency(h.total,f)}))).children(":last-child");a('[data-cart="decrement"]',i).bind("click",function(g){g.preventDefault();h.quantity--;h.quantity<1?b.remove(e):(b.save(),b.refresh())});a('[data-cart="increment"]',i).bind("click",
function(g){g.preventDefault();h.quantity++;b.save();b.refresh()});a('[data-cart="remove"]',i).bind("click",function(g){g.preventDefault();b.remove(e)})});a('[data-cart="open"]').unbind().bind("click",function(a){a.preventDefault();b.open(b.modal)});a('[data-cart="add"]').unbind().bind("click",function(d){d.preventDefault();b.add(a(this).data("options"))});a('[data-cart="checkout"]').unbind().bind("click",function(a){a.preventDefault();b.options.checkout.apply(b)});a('[data-cart="empty"]').unbind().bind("click",
function(a){a.preventDefault();b.clear();b.refresh()});a('[data-cart="quantity"]').html(this.quantity);a('[data-cart="total"]').html(Number.toCurrency(this.total,f));a('[data-cart="subtotal"]').html(Number.toCurrency(this.subTotal,f));a('[data-cart="taxtotal"]').html(Number.toCurrency(this.taxTotal,f))},update:function(){var b=this.options,f=0,d=0,e=0;a.each(this.items,function(a,i){i.update();f+=i.quantity;d+=i.quantity*i.price;e+=(i.tax||b.taxRate)*i.price});this.quantity=f;this.total=d+e;this.subTotal=
d;this.taxTotal=e;return this},load:function(){try{var b=this.items,f=a.parseJSON(this.storage.getItem(this.options.id))||[];a.each(f,function(a,d){b.push(new j(d))});this.update()}catch(d){}},save:function(){this.storage.setItem(this.options.id,JSON.stringify(this.items));this.update()},clear:function(){this.storage.clear();this.items=[];this.update()}});var j=function(b){a.extend(this,{name:"Item",code:"Code",price:0,quantity:1,total:0},b);this.update()};j.prototype=a.extend(j.prototype,{update:function(){this.total=
this.quantity*this.price}});a.cart=function(b){m||(m=new p(b));return m};a.template=function(b,f){return b.replace(/\{([\w\.]*)\}/g,function(b,e){var h=e.split("."),i=f[h.shift()];a.each(h,function(){i=i[this]});return i===null||i===void 0?"":i})};Array.remove=function(b,a,d){d=b.slice((d||a)+1||b.length);b.length=a<0?b.length+a:a;return b.push.apply(b,d)};Number.toCurrency=function(b,a,d,e,h){a=a||"";d=d==null?2:d;e=e||",";h=h||".";b=b.toFixed(d);d=RegExp("^(-?\\d{1,3})((?:\\d{3})+)(\\.(\\d{"+d+
"}))?$").exec(b);return a+(d?d[1]+d[2].replace(/\d{3}/g,h+"$&")+(d[4]?e+d[4]:""):b.replace(".",e))}})(jQuery);
typeof sessionStorage==="undefined"&&function(a){function m(){var g=k.document,n=/\bsessionStorage\b=([^;]+)(;|$)/,h=n.exec(g.cookie);if(h){i=a.decodeURIComponent(h[1]);f=j.encode(i,f);b=new b(k,"name");for(var n=b.key(),g=0,q=n.length,r={};g<q;++g)if((h=n[g]).indexOf(f)===0)d.push(h),r[h]=b.get(h),b.del(h);b=new b.constructor(k,"name",k.name);if(0<(this.length=d.length)){for(g=0,q=d.length,c=b.c,h=[];g<q;++g)h[g]=c.concat(b._c,b.escape(n=d[g]),c,c,(n=b.escape(r[n])).length,c,n);k.name+=h.join("")}}else g.cookie=
"sessionStorage="+a.encodeURIComponent(i=j.key(128)),f=j.encode(i,f),b=new b(k,"name",k.name),n.exec(g.cookie)||(d=null)}var k=a;try{for(;k!==k.top;)k=k.top}catch(p){}var j=function(b,a){return{decode:function(b,a){return this.encode(b,a)},encode:function(a,h){for(var d=a.length,n=h.length,l=[],i=[],e=0,f=0,k=0,m=0,j;e<256;++e)i[e]=e;for(e=0;e<256;++e)f=(f+(j=i[e])+a.charCodeAt(e%d))%256,i[e]=i[f],i[f]=j;for(f=0;k<n;++k)e=k%256,f=(f+(j=i[e]))%256,d=i[e]=i[f],i[f]=j,l[m++]=b(h.charCodeAt(k)^i[(d+j)%
256]);return l.join("")},key:function(i){for(var d=0,h=[];d<i;++d)h[d]=b(1+(a()*255<<0));return h.join("")}}}(a.String.fromCharCode,a.Math.random),b=function(b){function a(b,g,d){this._i=(this._data=d||"").length;(this._key=g)?this._storage=b:(this._storage={_key:b||""},this._key="_key")}function d(b,a){var g=this.c;return g.concat(this._c,this.escape(b),g,g,(a=this.escape(a)).length,g,a)}a.prototype.c=String.fromCharCode(1);a.prototype._c=".";a.prototype.clear=function(){this._storage[this._key]=
this._data};a.prototype.del=function(b){var a=this.get(b);a!==null&&(this._storage[this._key]=this._storage[this._key].replace(d.call(this,b,a),""))};a.prototype.escape=b.escape;a.prototype.get=function(b){var a=this._storage[this._key],g=this.c,d=a.indexOf(b=g.concat(this._c,this.escape(b),g,g),this._i),h=null;-1<d&&(d=a.indexOf(g,d+b.length-1)+1,h=a.substring(d,d=a.indexOf(g,d)),h=this.unescape(a.substr(++d,h)));return h};a.prototype.key=function(){for(var b=this._storage[this._key],a=this.c,g=
a+this._c,d=this._i,h=[],i=0,e=0;-1<(d=b.indexOf(g,d));)h[e++]=this.unescape(b.substring(d+=2,i=b.indexOf(a,d))),d=b.indexOf(a,i)+2,i=b.indexOf(a,d),d=1+i+1*b.substring(d,i);return h};a.prototype.set=function(b,a){this.del(b);this._storage[this._key]+=d.call(this,b,a)};a.prototype.unescape=b.unescape;return a}(a);if(Object.prototype.toString.call(a.opera)==="[object Opera]")history.navigationMode="compatible",b.prototype.escape=a.encodeURIComponent,b.prototype.unescape=a.decodeURIComponent;m.prototype=
{length:0,key:function(b){if(typeof b!=="number"||b<0||d.length<=b)throw"Invalid argument";return d[b]},getItem:function(a){a=f+a;if(h.call(e,a))return e[a];var d=b.get(a);d!==null&&(d=e[a]=j.decode(i,d));return d},setItem:function(a,h){this.removeItem(a);a=f+a;b.set(a,j.encode(i,e[a]=""+h));this.length=d.push(a)},removeItem:function(a){if(b.get(a=f+a)!==null)delete e[a],b.del(a),this.length=d.remove(a)},clear:function(){b.clear();e={};d.length=0}};var f=k.document.domain,d=[],e={},h=e.hasOwnProperty,
i;d.remove=function(a){a=this.indexOf(a);-1<a&&this.splice(a,1);return this.length};if(!d.indexOf)d.indexOf=function(a){for(var b=0,d=this.length;b<d;++b)if(this[b]===a)return b;return-1};if(k.sessionStorage)m=function(){},m.prototype=k.sessionStorage;m=new m;if(d!==null)a.sessionStorage=m}(window);var JSON;JSON||(JSON={});
(function(){function a(a){return a<10?"0"+a:a}function m(a){j.lastIndex=0;return j.test(a)?'"'+a.replace(j,function(a){var b=d[a];return typeof b==="string"?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function k(a,d){var g,n,j,q,r=b,o,l=d[a];l&&typeof l==="object"&&typeof l.toJSON==="function"&&(l=l.toJSON(a));typeof e==="function"&&(l=e.call(d,a,l));switch(typeof l){case "string":return m(l);case "number":return isFinite(l)?String(l):"null";case "boolean":case "null":return String(l);
case "object":if(!l)return"null";b+=f;o=[];if(Object.prototype.toString.apply(l)==="[object Array]"){q=l.length;for(g=0;g<q;g+=1)o[g]=k(g,l)||"null";j=o.length===0?"[]":b?"[\n"+b+o.join(",\n"+b)+"\n"+r+"]":"["+o.join(",")+"]";b=r;return j}if(e&&typeof e==="object"){q=e.length;for(g=0;g<q;g+=1)typeof e[g]==="string"&&(n=e[g],(j=k(n,l))&&o.push(m(n)+(b?": ":":")+j))}else for(n in l)Object.prototype.hasOwnProperty.call(l,n)&&(j=k(n,l))&&o.push(m(n)+(b?": ":":")+j);j=o.length===0?"{}":b?"{\n"+b+o.join(",\n"+
b)+"\n"+r+"}":"{"+o.join(",")+"}";b=r;return j}}if(typeof Date.prototype.toJSON!=="function")Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()};var p=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
j=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,b,f,d={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},e;if(typeof JSON.stringify!=="function")JSON.stringify=function(a,d,g){var j;f=b="";if(typeof g==="number")for(j=0;j<g;j+=1)f+=" ";else typeof g==="string"&&(f=g);if((e=d)&&typeof d!=="function"&&(typeof d!=="object"||typeof d.length!=="number"))throw Error("JSON.stringify");return k("",
{"":a})};if(typeof JSON.parse!=="function")JSON.parse=function(a,b){function d(a,e){var f,h,j=a[e];if(j&&typeof j==="object")for(f in j)Object.prototype.hasOwnProperty.call(j,f)&&(h=d(j,f),h!==void 0?j[f]=h:delete j[f]);return b.call(a,e,j)}var e,a=String(a);p.lastIndex=0;p.test(a)&&(a=a.replace(p,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return e=eval("("+a+")"),typeof b==="function"?d({"":e},""):e;throw new SyntaxError("JSON.parse");}})();
